### PR TITLE
Fix issues related to build solution and tests executions

### PR DESCRIPTION
**Pull request by TerraVenil**
- fix issue realted to building solution and tests executions;
- fix execution of task `Website-Create`;
- update NuGet spec due to changes of net46 -> net461;

### CODE REVIEW

**Comment by SharpeRAD** [comment]
Thank you 👍

**Comment by SharpeRAD** [comment]
Don't think I should have accepted this.

**Comment by TerraVenil** [comment]
Interesting point, so why did you accepted then? Do you have any issues?

**Comment by SharpeRAD** [comment]
#46

**Comment by TerraVenil** [comment]
Ok, I will investigate current issue if I break something. Thank you.

**Pull request merged**
