### PR TITLE
Added EnableDirectoryBrowsing

### LINKED ISSUE #27: Add a flag for directory browsing when adding a site
It should be possible to enable directory browsing.
See: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/directorybrowse
```csharp
using(ServerManager serverManager = new ServerManager()) { 
	Configuration config = serverManager.GetWebConfiguration("Contoso");

	ConfigurationSection directoryBrowseSection = config.GetSection("system.webServer/directoryBrowse");
	directoryBrowseSection["enabled"] = true;
	directoryBrowseSection["showFlags"] = @"Date, Time, Size, Extension";

	serverManager.CommitChanges();
}
```

### PR DESCRIPTION
**Pull request by Roemer**
Fixes #27 
A few notes:
- I added a cleanup to some tests so that the IIS is cleaned after a test.
- I had to make the ServerManager public (for the tests), that's why there are some renames.

### CODE REVIEW

**Comment by Roemer** [comment]
Wait with accepting. I might have a better approach. Details follow.

**Comment by Roemer** [comment]
I have rethought it and since this is nothing that is done on "creation" but afterwards with modifying the config, I think it would make more sense to have some kind of WebsiteConfigurationManager with maybe some aliases which allows to modify the configuration. This allows us to have also other configuration changes implemented.

**Comment by SharpeRAD** [comment]
If you went down that route it would also be good to create aliases for:
- SetAuthentication
- SetAuthorization

As well as:
- EnableDirectoryBrowsing
- DisableDirectoryBrowsing

I would still expect the EnableDirectoryBrowsing method to be called on website creation as that is the most common use case. 

What other configuration methods would you implement? As I think all of this could be done using the existing managers rather than separating them into a new WebsiteConfigurationManager.

**Comment by Roemer** [comment]
Have a look at this branch: https://github.com/Roemer/Cake.IIS/tree/ConfigurationEditing

**Comment by Roemer** [comment]
The configurations can be edited on website or application level.

**Comment by Roemer** [comment]
I don't like the WebConfigurationSettings class yet with the two subclasses.

**Comment by Roemer** [comment]
Hmm the configuration object is more complex than I thought. You can have sections, collections, elements and attributes (which are all needed for the Authentication/authorization, see https://stackoverflow.com/questions/9926683/configure-iis-authentication-settings-using-the-servermanager-class).
Nor sure if we really should map all that or if we maybe just should provide the Configuration object so one can do whatever he likes. What do you think?

**Comment by SharpeRAD** [comment]
Merging your other PR 😉

**Pull request closed without merging**
