### PR TITLE
Code cleanups

### LINKED ISSUE #29: Code inconsistencies / guidelines
There are quite some inconsistencies and also different coding guidelines used.

The code should be cleaned to make further extensions easier.

I can do a PR for that.

### PR DESCRIPTION
**Pull request by Roemer**
Just some various code cleanups to make the code more maintainable.
Fixes #29

### CODE REVIEW

**Comment by Roemer** [comment]
Oh and it's all just cosmetics and fully backward compatible.

**Comment by SharpeRAD** [comment]
I respect your right as an individual to format code any way you want in your own projects but I like regions, so NO...

**Comment by Roemer** [comment]
The problem is that it is very inconsistent. Some regions are missing, some have wrong "counts" (if i interpret the (x) correctly" and some are plain wrong named. I'm fine to keep them but it should be consistent. What about the other changes?

**Comment by Roemer** [comment]
Btw it's rather harsh to just close the PR. Making a comment to keep the regions would be fair enough.

**Pull request closed without merging**
