### PR TITLE
Add functionality to check if an application exists

### PR DESCRIPTION
**Pull request by Symbianx**
This PR adds methods and aliases to check if an application exists in a site.

### CODE REVIEW

**Comment by SharpeRAD** [comment]
Sorry had to fix a bug in bindings, please resolve the conflicts and I'll merge this PR.

**Comment by Symbianx** [comment]
@SharpeRAD done

**Comment by Symbianx** [comment]
@SharpeRAD done

**Comment by SharpeRAD** [comment]
Still got a conflict on this PR, will merge when you resolve it.

**Comment by Symbianx** [comment]
@SharpeRAD Should be good to go now! 👍

**Comment by ryanjfitz** [comment]
Thanks for developing and releasing this feature, however, shouldn't the SiteApplicationExists method for local IIS return bool, not void?

**Comment by Symbianx** [comment]
@ryanjfitz Indeed, working on it. Thanks for pointing that out 👍

**Pull request merged**
