### PR TITLE
Feature application site change physical path

### PR DESCRIPTION
**Pull request by Symbianx**
Added an alias to change the physical path of an application.

### CODE REVIEW

**Comment by SharpeRAD** [comment]
Not sure about this one as if we do it for one property then we should be consistent and do it for all properties. Id prefer to see a more generic "EditSite" method that takes in SiteSettings and only updates the properties you supply.

Can you explain your use-case?

**Comment by Symbianx** [comment]
Well, in our deploy processes, we change the physical path of the application to include the version of the deployed binaries. 
That's the only change we make to the Application/Site/AppPool after creating them, that's why I only considered the PhysicalPath change.

**Comment by SharpeRAD** [comment]
If you feel you need to keep previous copies on the machine aren't you better off having a separate versioned directory and moving files from there to your live website folder? Changing the path for every deployment means your application pool has unnecessarily broad access rights.

**Comment by Symbianx** [comment]
I am also using your WebDeploy addin to deploy the binaries, so I don't think that would be possible (or would it?).

**Comment by SharpeRAD** [comment]
Yea its possible to do it via WebDeploy or by Stopping the website and copying the files. I've found that its best to stop the website either way as we sometimes get locks on dll's when deploying legacy webForm apps via WebDeploy.

**Comment by Symbianx** [comment]
Ok, I'll leave it up to you, if you want to merge or not. I'll look at your Cake.WebDeploy project to find a way to change the Virtual Directory physical path.

**Pull request closed without merging**
