### PR TITLE
Need to also specify Microsoft.Web.Administration

### PR DESCRIPTION
**Pull request by superlogical**

### CODE REVIEW

**Comment by SharpeRAD** [comment]
Hey just noticed your PR, looks really good I'll accept it and publish a new nuget tonight :smile: 

I've got another PR I need to send to Cake that removes the need to reference "Microsoft.Web.Administration" (nested nuget packages) but I'll update the ReadMe with your changes tonight until that PR is accepted.

**Comment by superlogical** [comment]
Awesome thank you!!!

**Comment by superlogical** [comment]
I think you need to change the appveryor build script to not run the integration tests, otherwise the build will never pass

**Comment by SharpeRAD** [comment]
I ran it once and it threw an exception so I added the IIS service to the environment but its been queued for hours :angry: 

I'm assuming there's an backlog in AppVeyor and us freebie users are bottom of the pile...

**Comment by superlogical** [comment]
Argh makes sense :) I didn't know you could add an IIS instance to Appveyor.. that's kinda cool

**Comment by SharpeRAD** [comment]
Finally got the tests running in AppVeyor and found / fixed a few exceptions while i was there. Bit of a breaking change with PhysicalPath => DirectoryPath but it makes it more inline with Cake and allows for paths relative to the WorkingDirectory.

**Pull request merged**
